export const VANILLA_ITEMS = [
  'acacia button',
  'acacia door',
  'acacia fence gate',
  'acacia fence',
  'acacia leaves',
  'acacia log',
  'acacia planks',
  'acacia pressure plate',
  'acacia sapling',
  'acacia sign',
  'acacia slab',
  'acacia stairs',
  'acacia trapdoor',
  'acacia wall sign',
  'acacia wood',
  'activator rail',
  'air',
  'allium',
  'ancient debris',
  'andesite slab',
  'andesite stairs',
  'andesite wall',
  'andesite',
  'anvil',
  'attached melon stem',
  'attached pumpkin stem',
  'azure bluet',
  'bamboo sapling',
  'bamboo',
  'barrel',
  'barrier',
  'basalt',
  'beacon',
  'bedrock',
  'bee spawn egg',
  'beehive',
  'beetroots',
  'bell',
  'birch button',
  'birch door',
  'birch fence gate',
  'birch fence',
  'birch leaves',
  'birch log',
  'birch planks',
  'birch pressure plate',
  'birch sapling',
  'birch sign',
  'birch slab',
  'birch stairs',
  'birch trapdoor',
  'birch wall sign',
  'birch wood',
  'black bed',
  'black carpet',
  'black concrete powder',
  'black concrete',
  'black glazed terracotta',
  'black shulker box',
  'black stained glass pane',
  'black stained glass',
  'black terracotta',
  'black wall banner',
  'black wool',
  'blackstone slab',
  'blackstone stairs',
  'blackstone wall',
  'blackstone',
  'blast furnace',
  'blue bed',
  'blue carpet',
  'blue concrete powder',
  'blue concrete',
  'blue glazed terracotta',
  'blue ice',
  'blue orchid',
  'blue shulker box',
  'blue stained glass pane',
  'blue stained glass',
  'blue terracotta',
  'blue wall banner',
  'blue wool',
  'bone block',
  'bookshelf',
  'brain coral block',
  'brain coral fan',
  'brain coral wall fan',
  'brain coral',
  'brick slab',
  'brick stairs',
  'brick wall',
  'bricks',
  'brown bed',
  'brown carpet',
  'brown concrete powder',
  'brown concrete',
  'brown glazed terracotta',
  'brown mushroom block',
  'brown mushroom',
  'brown shulker box',
  'brown stained glass pane',
  'brown stained glass',
  'brown terracotta',
  'brown wall banner',
  'brown wool',
  'bubble column',
  'bubble coral block',
  'bubble coral fan',
  'bubble coral wall fan',
  'bubble coral',
  'cactus',
  'cake',
  'campfire',
  'carrots',
  'cartography table',
  'carved pumpkin',
  'cave air',
  'chain command block',
  'chain',
  'chest',
  'chipped anvil',
  'chiseled nether bricks',
  'chiseled polished blackstone',
  'chiseled quartz block',
  'chiseled red sandstone',
  'chiseled sandstone',
  'chiseled stone bricks',
  'chorus flower',
  'chorus plant',
  'clay',
  'coal block',
  'coal ore',
  'coarse dirt',
  'cobblestone slab',
  'cobblestone stairs',
  'cobblestone wall',
  'cobblestone',
  'cobweb',
  'cocoa',
  'command block',
  'comparator',
  'composter',
  'conduit',
  'cornflower',
  'cracked nether bricks',
  'cracked polished blackstone bricks',
  'cracked stone bricks',
  'crafting table',
  'creeper head',
  'creeper wall head',
  'crimson button',
  'crimson door',
  'crimson fence gate',
  'crimson fence',
  'crimson fungus',
  'crimson hyphae',
  'crimson nylium',
  'crimson planks',
  'crimson pressure plate',
  'crimson roots',
  'crimson sign',
  'crimson slab',
  'crimson stairs',
  'crimson stem',
  'crimson trapdoor',
  'crimson wall sign',
  'crying obsidian',
  'cut red sandstone slab',
  'cut red sandstone',
  'cut sandstone slab',
  'cut sandstone',
  'cyan bed',
  'cyan carpet',
  'cyan concrete powder',
  'cyan concrete',
  'cyan glazed terracotta',
  'cyan shulker box',
  'cyan stained glass pane',
  'cyan stained glass',
  'cyan terracotta',
  'cyan wall banner',
  'cyan wool',
  'damaged anvil',
  'dandelion',
  'dark oak button',
  'dark oak door',
  'dark oak fence gate',
  'dark oak fence',
  'dark oak leaves',
  'dark oak log',
  'dark oak planks',
  'dark oak pressure plate',
  'dark oak sapling',
  'dark oak sign',
  'dark oak slab',
  'dark oak stairs',
  'dark oak trapdoor',
  'dark oak wall sign',
  'dark oak wood',
  'dark prismarine slab',
  'dark prismarine stairs',
  'dark prismarine',
  'daylight detector',
  'dead brain coral block',
  'dead brain coral fan',
  'dead brain coral wall fan',
  'dead brain coral',
  'dead bubble coral block',
  'dead bubble coral fan',
  'dead bubble coral wall fan',
  'dead bubble coral',
  'dead bush',
  'dead fire coral block',
  'dead fire coral fan',
  'dead fire coral wall fan',
  'dead fire coral',
  'dead horn coral block',
  'dead horn coral fan',
  'dead horn coral wall fan',
  'dead horn coral',
  'dead tube coral block',
  'dead tube coral fan',
  'dead tube coral wall fan',
  'dead tube coral',
  'detector rail',
  'diamond block',
  'diamond ore',
  'diorite slab',
  'diorite stairs',
  'diorite wall',
  'diorite',
  'dirt',
  'dispenser',
  'dragon egg',
  'dragon head',
  'dragon wall head',
  'dried kelp block',
  'dropper',
  'emerald block',
  'emerald ore',
  'enchanting table',
  'end gateway',
  'end portal frame',
  'end portal',
  'end rod',
  'end stone brick slab',
  'end stone brick stairs',
  'end stone brick wall',
  'end stone bricks',
  'end stone',
  'ender chest',
  'farmland',
  'fern',
  'fire coral block',
  'fire coral fan',
  'fire coral wall fan',
  'fire coral',
  'fire',
  'fletching table',
  'frosted ice',
  'furnace',
  'gilded blackstone',
  'glass pane',
  'glass',
  'glowstone',
  'gold block',
  'gold ore',
  'granite slab',
  'granite stairs',
  'granite wall',
  'granite',
  'grass block',
  'grass path',
  'grass',
  'gravel',
  'gray bed',
  'gray carpet',
  'gray concrete powder',
  'gray concrete',
  'gray glazed terracotta',
  'gray shulker box',
  'gray stained glass pane',
  'gray stained glass',
  'gray terracotta',
  'gray wall banner',
  'gray wool',
  'green bed',
  'green carpet',
  'green concrete powder',
  'green concrete',
  'green glazed terracotta',
  'green shulker box',
  'green stained glass pane',
  'green stained glass',
  'green terracotta',
  'green wall banner',
  'green wool',
  'grindstone',
  'hay block',
  'heavy weighted pressure plate',
  'honey block',
  'honeycomb block',
  'hopper',
  'horn coral block',
  'horn coral fan',
  'horn coral wall fan',
  'horn coral',
  'ice',
  'infested chiseled stone bricks',
  'infested cobblestone',
  'infested cracked stone bricks',
  'infested mossy stone bricks',
  'infested stone bricks',
  'infested stone',
  'iron bars',
  'iron block',
  'iron door',
  'iron ore',
  'iron trapdoor',
  'jack o lantern',
  'jigsaw',
  'jukebox',
  'jungle button',
  'jungle door',
  'jungle fence gate',
  'jungle fence',
  'jungle leaves',
  'jungle log',
  'jungle planks',
  'jungle pressure plate',
  'jungle sapling',
  'jungle sign',
  'jungle slab',
  'jungle stairs',
  'jungle trapdoor',
  'jungle wall sign',
  'jungle wood',
  'kelp plant',
  'ladder',
  'lantern',
  'lapis block',
  'lapis ore',
  'large fern',
  'lava',
  'lectern',
  'lever',
  'light blue bed',
  'light blue carpet',
  'light blue concrete powder',
  'light blue concrete',
  'light blue glazed terracotta',
  'light blue shulker box',
  'light blue stained glass pane',
  'light blue stained glass',
  'light blue terracotta',
  'light blue wall banner',
  'light blue wool',
  'light gray bed',
  'light gray carpet',
  'light gray concrete powder',
  'light gray concrete',
  'light gray glazed terracotta',
  'light gray shulker box',
  'light gray stained glass pane',
  'light gray stained glass',
  'light gray terracotta',
  'light gray wall banner',
  'light gray wool',
  'light weighted pressure plate',
  'lilac',
  'lily of the valley',
  'lily pad',
  'lime bed',
  'lime carpet',
  'lime concrete powder',
  'lime concrete',
  'lime glazed terracotta',
  'lime shulker box',
  'lime stained glass pane',
  'lime stained glass',
  'lime terracotta',
  'lime wall banner',
  'lime wool',
  'lodestone',
  'loom',
  'magenta bed',
  'magenta carpet',
  'magenta concrete powder',
  'magenta concrete',
  'magenta glazed terracotta',
  'magenta shulker box',
  'magenta stained glass pane',
  'magenta stained glass',
  'magenta terracotta',
  'magenta wall banner',
  'magenta wool',
  'magma block',
  'melon stem',
  'melon',
  'mossy cobblestone slab',
  'mossy cobblestone stairs',
  'mossy cobblestone wall',
  'mossy cobblestone',
  'mossy stone brick slab',
  'mossy stone brick stairs',
  'mossy stone brick wall',
  'mossy stone bricks',
  'moving piston',
  'mushroom stem',
  'mycelium',
  'nether brick fence',
  'nether brick slab',
  'nether brick stairs',
  'nether brick wall',
  'nether bricks',
  'nether gold ore',
  'nether portal',
  'nether quartz ore',
  'nether sprouts',
  'nether wart block',
  'netherite block',
  'netherrack',
  'note block',
  'oak button',
  'oak door',
  'oak fence gate',
  'oak fence',
  'oak leaves',
  'oak log',
  'oak planks',
  'oak pressure plate',
  'oak sapling',
  'oak sign',
  'oak slab',
  'oak stairs',
  'oak trapdoor',
  'oak wall sign',
  'oak wood',
  'observer',
  'obsidian',
  'orange bed',
  'orange carpet',
  'orange concrete powder',
  'orange concrete',
  'orange glazed terracotta',
  'orange shulker box',
  'orange stained glass pane',
  'orange stained glass',
  'orange terracotta',
  'orange tulip',
  'orange wall banner',
  'orange wool',
  'oxeye daisy',
  'packed ice',
  'peony',
  'petrified oak slab',
  'pink bed',
  'pink carpet',
  'pink concrete powder',
  'pink concrete',
  'pink glazed terracotta',
  'pink shulker box',
  'pink stained glass pane',
  'pink stained glass',
  'pink terracotta',
  'pink tulip',
  'pink wall banner',
  'pink wool',
  'piston head',
  'piston',
  'player head',
  'player wall head',
  'podzol',
  'polished andesite slab',
  'polished andesite stairs',
  'polished andesite',
  'polished basalt',
  'polished blackstone brick slab',
  'polished blackstone brick stairs',
  'polished blackstone brick wall',
  'polished blackstone bricks',
  'polished blackstone button',
  'polished blackstone pressure plate',
  'polished blackstone slab',
  'polished blackstone stairs',
  'polished blackstone wall',
  'polished blackstone',
  'polished diorite slab',
  'polished diorite stairs',
  'polished diorite',
  'polished granite slab',
  'polished granite stairs',
  'polished granite',
  'poppy',
  'potatoes',
  'potted acacia sapling',
  'potted allium',
  'potted azure bluet',
  'potted bamboo',
  'potted birch sapling',
  'potted blue orchid',
  'potted brown mushroom',
  'potted cactus',
  'potted cornflower',
  'potted crimson fungus',
  'potted crimson roots',
  'potted dandelion',
  'potted dark oak sapling',
  'potted dead bush',
  'potted fern',
  'potted jungle sapling',
  'potted lily of the valley',
  'potted oak sapling',
  'potted orange tulip',
  'potted oxeye daisy',
  'potted pink tulip',
  'potted poppy',
  'potted red mushroom',
  'potted red tulip',
  'potted spruce sapling',
  'potted warped fungus',
  'potted warped roots',
  'potted white tulip',
  'potted wither rose',
  'powered rail',
  'prismarine brick slab',
  'prismarine brick stairs',
  'prismarine bricks',
  'prismarine slab',
  'prismarine stairs',
  'prismarine wall',
  'prismarine',
  'pumpkin stem',
  'pumpkin',
  'purple bed',
  'purple carpet',
  'purple concrete powder',
  'purple concrete',
  'purple glazed terracotta',
  'purple shulker box',
  'purple stained glass pane',
  'purple stained glass',
  'purple terracotta',
  'purple wall banner',
  'purple wool',
  'purpur block',
  'purpur pillar',
  'purpur slab',
  'purpur stairs',
  'quartz block',
  'quartz bricks',
  'quartz pillar',
  'quartz slab',
  'quartz stairs',
  'rail',
  'red bed',
  'red carpet',
  'red concrete powder',
  'red concrete',
  'red glazed terracotta',
  'red mushroom block',
  'red mushroom',
  'red nether brick slab',
  'red nether brick stairs',
  'red nether brick wall',
  'red nether bricks',
  'red sand',
  'red sandstone slab',
  'red sandstone stairs',
  'red sandstone wall',
  'red sandstone',
  'red shulker box',
  'red stained glass pane',
  'red stained glass',
  'red terracotta',
  'red tulip',
  'red wall banner',
  'red wool',
  'redstone block',
  'redstone lamp',
  'redstone ore',
  'redstone torch',
  'redstone wall torch',
  'redstone wire',
  'repeater',
  'repeating command block',
  'respawn anchor',
  'rose bush',
  'sand',
  'sandstone slab',
  'sandstone stairs',
  'sandstone wall',
  'sandstone',
  'scaffolding',
  'sea lantern',
  'sea pickle',
  'seagrass',
  'shroomlight',
  'shulker box',
  'skeleton skull',
  'skeleton wall skull',
  'slime block',
  'smithing table',
  'smoker',
  'smooth quartz slab',
  'smooth quartz stairs',
  'smooth quartz',
  'smooth red sandstone slab',
  'smooth red sandstone stairs',
  'smooth red sandstone',
  'smooth sandstone slab',
  'smooth sandstone stairs',
  'smooth sandstone',
  'smooth stone slab',
  'smooth stone',
  'snow block',
  'snow',
  'soul campfire',
  'soul fire',
  'soul lantern',
  'soul sand',
  'soul soil',
  'soul torch',
  'soul wall torch',
  'spawner',
  'sponge',
  'spruce button',
  'spruce door',
  'spruce fence gate',
  'spruce fence',
  'spruce leaves',
  'spruce log',
  'spruce planks',
  'spruce pressure plate',
  'spruce sapling',
  'spruce sign',
  'spruce slab',
  'spruce stairs',
  'spruce trapdoor',
  'spruce wall sign',
  'spruce wood',
  'sticky piston',
  'stone brick slab',
  'stone brick stairs',
  'stone brick wall',
  'stone bricks',
  'stone button',
  'stone pressure plate',
  'stone slab',
  'stone stairs',
  'stone',
  'stonecutter',
  'stripped acacia log',
  'stripped acacia wood',
  'stripped birch log',
  'stripped birch wood',
  'stripped crimson hyphae',
  'stripped crimson stem',
  'stripped dark oak log',
  'stripped dark oak wood',
  'stripped jungle log',
  'stripped jungle wood',
  'stripped oak log',
  'stripped oak wood',
  'stripped spruce log',
  'stripped spruce wood',
  'stripped warped hyphae',
  'stripped warped stem',
  'structure block',
  'structure void',
  'sunflower',
  'sweet berry bush',
  'tall grass',
  'tall seagrass',
  'target',
  'terracotta',
  'tnt',
  'torch',
  'trapped chest',
  'tripwire hook',
  'tripwire',
  'tube coral block',
  'tube coral fan',
  'tube coral wall fan',
  'tube coral',
  'turtle egg',
  'twisting vines plant',
  'twisting vines',
  'vine',
  'void air',
  'wall sign',
  'wall torch',
  'warped button',
  'warped door',
  'warped fence gate',
  'warped fence',
  'warped fungus',
  'warped hyphae',
  'warped nylium',
  'warped planks',
  'warped pressure plate',
  'warped roots',
  'warped sign',
  'warped slab',
  'warped stairs',
  'warped stem',
  'warped trapdoor',
  'warped wall sign',
  'warped wart block',
  'water',
  'weeping vines plant',
  'weeping vines',
  'wet sponge',
  'white bed',
  'white carpet',
  'white concrete powder',
  'white concrete',
  'white glazed terracotta',
  'white shulker box',
  'white stained glass pane',
  'white stained glass',
  'white terracotta',
  'white tulip',
  'white wall banner',
  'white wool',
  'wither rose',
  'wither skeleton skull',
  'wither skeleton wall skull',
  'yellow bed',
  'yellow carpet',
  'yellow concrete powder',
  'yellow concrete',
  'yellow glazed terracotta',
  'yellow shulker box',
  'yellow stained glass pane',
  'yellow stained glass',
  'yellow terracotta',
  'yellow wall banner',
  'yellow wool',
  'zombie head',
  'zombie wall head',
]
